[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Protection renforcée contre XSS (sans unsafe-inline/unsafe-eval)
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com; style-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com https://fonts.cdnfonts.com; img-src 'self' data: https: blob:; media-src 'self' https:; object-src 'none'; frame-src 'none'; connect-src 'self' https://xrmcwbivgzxtzakiexnq.supabase.co wss://xrmcwbivgzxtzakiexnq.supabase.co; worker-src 'self' blob:; child-src 'self'; form-action 'self'; base-uri 'self'; manifest-src 'self'"
    
    # Permissions Policy - Contrôle des APIs du navigateur
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(self), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
    
    # Strict Transport Security - Force HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Protection contre le clickjacking
    X-Frame-Options = "DENY"
    
    # Protection XSS
    X-XSS-Protection = "1; mode=block"
    
    # Prévention du MIME sniffing
    X-Content-Type-Options = "nosniff"
    
    # Politique de référent
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Désactiver les informations du serveur
    X-Powered-By = ""
    
    # Cross-Origin Embedder Policy (relaxé pour compatibilité)
    Cross-Origin-Embedder-Policy = "unsafe-none"
    
    # Cross-Origin Opener Policy
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    
    # Cross-Origin Resource Policy
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/logo.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "image/svg+xml"